name: Bug report
description: Report an error or unexpected behaviour
labels: [bug]

body:
  - type: markdown
    attributes:
      value: |
        Welcome to the Quarto Wizard GitHub repository!
        We are always happy to hear feedback from our users.

        - If you want to ask for a feature, please use the [Feature Requests GitHub Discussions](https://github.com/mcanouil/quarto-wizard/discussions/categories/feature-requests).
        - If you want to ask for help, please use the [Q&A GitHub Discussions](https://github.com/mcanouil/quarto-wizard/discussions/categories/q-a).
        - If you're reporting an issue with Quarto CLI, please visit <https://github.com/quarto-dev/quarto-cli>.

        Thank you for using Quarto Wizard!

  - type: textarea
    attributes:
      label: Bug description
      description: Description of the bug.
      placeholder: Please describe the bug here.

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: |
        Tell us how to reproduce this bug.

  - type: textarea
    attributes:
      label: Actual behaviour
      description: Tell us what happens instead.

  - type: textarea
    attributes:
      label: Expected behaviour
      description: Tell us what should happen.

  - type: textarea
    attributes:
      label: Your environment
      description: |
        Please document the IDE (_e.g._ VSCode, Positron, _etc._), its version, and the operating system you're running (_e.g., MacOS Ventura 13.4, Windows 11, Linux Debian 11, _etc._).
      placeholder: |
        - IDE: VSCode 1.96
        - OS: MacOS Ventura 13.4

  - type: markdown
    attributes:
      value: "_Thanks for submitting this bug report!_"
