name: Check changelog

on:
  workflow_dispatch:
    inputs:
      type:
        type: choice
        description: Type
        options:
          - release
          - pre-release
        default: pre-release
      date:
        type: string
        description: 'Date ("YYYY-MM-DD" or "today")'
        default: today

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    env:
      BRANCH: ci/update-changelog-release
      GITHUB_TOKEN: ${{ secrets.github_token }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for "unreleased" in CHANGELOG.md
        id: check_unreleased
        shell: bash
        run: |
          if grep -q "unreleased" CHANGELOG.md; then
            echo "UNRELEASED_FOUND=true" >> $GITHUB_OUTPUT
          else
            echo "UNRELEASED_FOUND=false" >> $GITHUB_OUTPUT
          fi

      - name: Update date in CHANGELOG.md
        if: ${{ steps.check_unreleased.outputs.UNRELEASED_FOUND == 'true' }}
        shell: bash
        run: |
          if [ "${{ github.event.inputs.date }}" = "today" ]; then
            RELEASE_DATE=$(date +%Y-%m-%d)
          else
            RELEASE_DATE=${{ github.event.inputs.date }}
          fi
          sed -i "s/unreleased/${RELEASE_DATE}/" CHANGELOG.md
