name: Publish VS Code Extension

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4

    - name: Install dependencies
      run: npm install

    - name: Install vsce
      run: npm install -g @vscode/vsce

    - name: Package extension
      id: package
      run: |
        if [ "${{ github.event.release.prerelease }}" = "true" ]; then
          vsce package --pre-release
        else
          vsce package
        fi

    - name: Upload VSIX artifact
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        name: quarto-wizard-${{ github.event.release.tag_name }}.vsix
        path: quarto-wizard-${{ github.event.release.tag_name }}.vsix

    - name: Publish extension to Visual Studio Marketplace
      env:
        VS_MARKETPLACE_TOKEN: ${{ secrets.VS_MARKETPLACE_TOKEN }}
      run: |
        vsce login ${{ github.repository_owner }}
        if [ "${{ github.event.release.prerelease }}" = "true" ]; then
          vsce publish --pre-release
        else
          vsce publish
        fi

    - name: Publish extension to Open VSX Registry
      env:
        OPEN_VSX_REGISTRY_TOKEN: ${{ secrets.OPEN_VSX_REGISTRY_TOKEN }}
      run: |
        vsce login ${{ github.repository_owner }}
        if [ "${{ github.event.release.prerelease }}" = "true" ]; then
          vsce publish --pre-release
        else
          vsce publish
        fi
