name: Release and Publish VS Code Extension

on:
  workflow_dispatch:
    inputs:
      prerelease:
        description: 'Is this a pre-release?'
        required: true
        type: boolean
        default: true

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4

    - name: Install dependencies
      run: npm install

    - name: Install Visual Studio Code Extension Manager
      run: npm install -g @vscode/vsce
    
    - name: Set version
      run: |
        echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

    - name: Set status
      run: |
        if [ "${{ github.event.inputs.prerelease }}" = "true" ]; then
          echo "STATUS=prerelease" >> $GITHUB_ENV
        else
          echo "STATUS=''" >> $GITHUB_ENV
        fi
    
    - name: Set changelog
      run: |
        awk -v version="## ${VERSION}" '
          $0 == version {flag=1; next}
          /^## / && flag {flag=0}
          flag
        ' CHANGELOG.md >CHANGELOG
        echo "CHANGELOG=${CHANGELOG}" >> $GITHUB_ENV

    - name: Package extension
      env:
        GH_TOKEN: ${{ secrets.github_token }}
        VERSION: ${{ env.VERSION }}
        STATUS: ${{ env.STATUS }}
        CHANGELOG: ${{ env.CHANGELOG }}
      run: |
        vsce package ${STATUS}
        gh release create ${VERSION} \
          ${STATUS} \
          --title ${VERSION} \
          --notes ${CHANGELOG}

    - name: Publish extension to Visual Studio Marketplace
      if: false
      env:
        VS_MARKETPLACE_TOKEN: ${{ secrets.VS_MARKETPLACE_TOKEN }}
      run: |
        vsce publish --pre-release --pat ${VS_MARKETPLACE_TOKEN}

    - name: Publish extension to Open VSX Registry
      if: false
      env:
        OPEN_VSX_REGISTRY_TOKEN: ${{ secrets.OPEN_VSX_REGISTRY_TOKEN }}
      run: |
        vsce publish --pre-release --pat ${OPEN_VSX_REGISTRY_TOKEN}
